In [15]:
import pyaudio
import struct
import numpy as np
from matplotlib import pyplot as plt

In [29]:
CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 1
RATE = 44100

In [26]:
p = pyaudio.PyAudio()

stream = p.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)

data = stream.read(CHUNK)
data_int = np.array(struct.unpack(str(2 * CHUNK) + 'B', data), dtype='b')[::2] + 127 
data_int

array([127, 127, 127, ..., 127, 127, 127], dtype=int8)

In [18]:
fig, ax = plt.subplots()
ax.plot(data_int, '-')

x = np.arange(0, 2 * CHUNK, 2)
line, = ax.plot(x, np.random.rand(CHUNK))

ax.set_ylim(0, 255)
ax.set_xlim(0, 2 * CHUNK)

(0.0, 2048.0)

In [32]:
stream = p.open(
    format=FORMAT,
    channels=CHANNELS,
    rate=RATE,
    input=True,
    output=True,
    frames_per_buffer=CHUNK
)

while True:
    data = stream.read(CHUNK)
    data_int = struct.unpack(str(2 * CHUNK) + 'B', data)
    data_int = np.array(data_int, dtype='b')[::2] + 127
    try:
        line.set_ydata(data_int)
        fig.canvas.draw()
        fig.canvas.flush_events()
    except:
        print("...")

[127 127 127 ... 127 127 127]
[127 127 127 ... 127 127 127]
[ -47  -46  -18 ... -100  126 -112]
[-100 -114 -123 ...  -63   96   83]
[ -77   93   36 ... -108 -118 -116]
[-111  112   98 ...   67   74   84]
[ 88  70  61 ... -62 -44 -25]
[-12  -2   0 ...  84  75  76]
[  82  104 -109 ...   54   46   34]
[ 12  -8 -15 ... -87 -75 -63]
[-54 -42 -30 ... 114 117 116]
[108  96  85 ...  75  61  44]
[ 31  19   1 ... -91 -81 -74]
[ -85  -91  -90 ...  119  126 -125]
[-110  -93  -78 ...   71   65   63]
[55 48 28 ... 48 47 42]
[ 34  25   7 ... 108 105 105]
[104  93  83 ...  -4  -9 -23]
[-45 -69 -81 ... -45 -46 -54]
[-71 -85 -97 ... -20 -13  -6]
[   7   17   27 ... -125  104   87]
[ 88  96 103 ...  -8   7  30]
[49 63 82 ... 59 70 81]
[  91  100  111 ... -104 -115  124]
[112 107 104 ...  -9 -22 -44]
[ -69  -89 -100 ...  117  126 -115]
[-104  -97 -101 ...  -22  -11   -6]
[  3  11  15 ... -25 -36 -46]
[-51 -56 -57 ... -17 -30 -45]
[-50 -45 -34 ... -11 -10 -10]
[ -5  -3 -12 ... -29 -59 -74]
[-79 -81 -78 ...

[ 68  91 104 ... -11  55 121]
[ -88  -59  -35 ... -124 -108  -95]
[-82 -75 -62 ...  50  36  24]
[ -1 -33 -62 ... -26 -27 -21]
[-21 -29 -25 ...  37  28  17]
[   4  -18  -36 ... -118  113   95]
[84 81 95 ... 29 27 26]
[10  2  5 ... 14  1 -7]
[ -12  -13  -12 ...  102  115 -125]
[-107  -92  -77 ... -120  100   78]
[  69   56   50 ... -116 -127  125]
[-128 -125 -125 ...  -40  -28  -22]
[-26 -24 -23 ...  92  85  77]
[  77   72   61 ... -104  -89  -74]
[-66 -67 -80 ... -59 -49 -31]
[-13   2  13 ...  10  30  46]
[64 66 72 ... 59 61 62]
[ 59  63  61 ... -93 -95 -89]
[-72 -46 -26 ...  -6  -5   2]
[ 30  47  62 ...  -5 -19 -39]
[-58 -70 -80 ... -73 -67 -56]
[-48 -38 -28 ... -81 -81 -83]
[-83 -80 -79 ...  73  57  23]
[-10 -44 -77 ... 116 115 125]
[-113  -95  -67 ...   47   83  119]
[-114  -92  -85 ...   -8  -12    0]
[25 53 73 ... 94 86 81]
[ 76  67  60 ... -97 -75 -53]
[-40 -31 -19 ... -82 -81 -73]
[ -61  -49  -41 ... -119  106   85]
[ 73  65  58 ... -29 -35 -31]
[-18   4  37 ...  60  70  78]
[ 84

[ -17  -39  -62 ...  104  125 -106]
[-87 -73 -52 ... -24   6  27]
[47 74 89 ... 24 34 48]
[ 58  63  57 ... -90 -81 -71]
[-65 -64 -61 ...  73  47  14]
[-16 -45 -72 ...  86  86  82]
[ 88  90 103 ...  28  30  34]
[ 39  43  51 ... -26 -43 -56]
[-63 -67 -68 ...  -9 -24 -42]
[-64 -81 -94 ... -52 -34 -26]
[-31 -37 -46 ...  -7 -19 -21]
[-27 -22 -12 ... -67 -55 -48]
[-48 -55 -71 ...  61  62  58]
[56 60 69 ... 27 49 68]
[ 88 101 112 ...  97  84  69]
[  57   32    3 ...  106  123 -113]
[-109 -110 -122 ...  -80 -114  115]
[ 98  97 105 ... -11 -52 -84]
[-97 -90 -65 ...  27  28  18]
[  13   11    1 ...  -99 -105 -108]
[ -97  -81  -63 ... -115 -107 -102]
[-100  -96 -101 ...   90   73   57]
[ 34  -1 -29 ... -20 -19 -19]
[-8 14 43 ... 61 80 88]
[84 81 79 ... 28 19  9]
[ -3 -14 -12 ...  20  27  33]
[  37   32   19 ...  -76  -97 -116]
[120 100  79 ...  77  69  73]
[ 85  97 110 ...  -7   0   0]
[ -9 -22 -34 ... 102  52  19]
[  5   4   9 ... -67 -82 -96]
[-115  111   91 ...  124  117  105]
[ 89  66  48 ...

KeyboardInterrupt: 